/* [${LIB_NAME}]
 * Edition: ${LIB_EDITION}
 * Version: ${LIB_VER}
 * Qt Version: ${QT_VER}
 * Platform: ${PLATFORM}
 * Build Date: ${BUILD_DATE}
*/
#ifndef ${MAIN_INCLUDE_NAME}
#define ${MAIN_INCLUDE_NAME}

#define ${LIB_NAME_UC}_VERSION ${LIB_VER}
#define ${LIB_NAME_UC}_VERSION_MAJOR ${LIB_VER_MAJOR}
#define ${LIB_NAME_UC}_VERSION_MINOR ${LIB_VER_MINOR}
#define ${LIB_NAME_UC}_VERSION_REVISION ${LIB_VER_REV}
#define ${LIB_NAME_UC}_VERSION_BUILD ${LIB_VER_BUILD}

${COMPONENT_INCLUDE_FILES}
#endif // ${MAIN_INCLUDE_NAME}