name: Linux - Build Qx
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
    outputs:
      qt_shared_artifact_name:
        description: "Qx (Qt shared) build artifact"
        value: ${{ jobs.build-qx.outputs.qt_shared_artifact_name }}
      qt_static_artifact_name:
        description: "Qx (Qt static) build artifact"
        value: ${{ jobs.build-qx.outputs.qt_static_artifact_name }}
env:
  general_download_dir: ${{ github.workspace }}/Download
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qx_src_suffix: Qx/Source
  qx_src_dir: ${{ github.workspace }}/Qx/Source
  qx_build_dir: ${{ github.workspace }}/Qx/Build

jobs:
  build-qx:
    name: Build Qx - Linux (Debug/Release)
    strategy:
      matrix:
        qt_linkage: [shared, static]
    runs-on: ubuntu-20.04
    env:
      c_comp: clang-12
      cxx_comp: clang++-12
      cmake_gen: Ninja Multi-Config
    outputs:
      qt_shared_artifact_name: ${{ steps.get_artifact_name.outputs.qt_shared_artifact_name }}
      qt_static_artifact_name: ${{ steps.get_artifact_name.outputs.qt_static_artifact_name }}
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qx_package_path=${{ env.qx_build_dir }}/out/dist" >> $GITHUB_ENV
        qx_install_path="${{ env.qx_build_dir }}/out/install"
        echo "qx_install_path=$qx_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.0
        os: linux
        compiler: clang
        linkage: ${{ matrix.qt_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install XCB Related libs
      run: sudo apt-get install libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-*-dev
    - name: Install Doxygen
      uses: oblivioncth/actions/ubuntu/install-doxygen-from-sourceforge@dev
      with:
        version: 1.9.4
    - name: Install Graphviz
      run: sudo apt-get install graphviz
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz-dev
    - name: Checkout Qx
      uses: actions/checkout@v3
      with:
        path: ${{ env.qx_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install Qx
      working-directory: ${{ env.qx_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$qx_src_dir" -B "$qx_build_dir" -D QX_DOCS_TARGET=ON -D CMAKE_CXX_COMPILER="$cxx_comp" -D CMAKE_C_COMPILER="$c_comp"
        echo Changing to build directory...
        cd "$qx_build_dir"
        echo Building Qx debug...
        cmake --build . --target all --config Debug
        echo Building Qx release...
        cmake --build . --target all --config Release
        echo Building Qx docs...
        cmake --build . --target qx_docs --config Release
        echo Installing Qx Debug
        cmake --build . --target install --config Debug
        echo Installing Qx Release/Docs...
        cmake --build . --target install --config Release
        echo Packaging Qx...
        cpack -C "Debug;Release"
        echo Build complete.
    - name: Get Qx artifact name
      id: get_artifact_name
      run: |
        cpack_name=$(find "${{ env.qx_package_path }}" -type f -name "*.zip")
        artifact_name=$(basename "$cpack_name" .zip)
        echo "qx_current_artifact_name=$artifact_name" >> $GITHUB_ENV
        echo "qt_${{ matrix.qt_linkage }}_artifact_name=$artifact_name" >> $GITHUB_OUTPUT
    - name: Upload Qx build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.qx_current_artifact_name }}
        path: ${{ env.qx_install_path }}
        if-no-files-found: error
