name: Qx Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build Qx
    uses: oblivioncth/actions/.github/workflows/build-cxx-project.yml@feature/upgrades
    secrets:
      ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
  