name: Windows - Build Qx
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
    outputs:
      doc_artifact_name:
        description: "Name of artifact used to update docs"
        value: ${{ jobs.build-qx.outputs.doc_artifact_name }}
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qx_src_suffix: Qx/Source
  qx_src_dir: ${{ github.workspace }}/Qx/Source
  qx_build_dir: ${{ github.workspace }}/Qx/Build

jobs:
  build-qx:
    name: Build Qx - Windows (Debug/Release)
    strategy:
      matrix:
        lib_linkage: [shared, static]
        include:
          - lib_linkage: shared
            cmake_bsl: ON
          - lib_linkage: static
            cmake_bsl: OFF
    runs-on: windows-latest
    env:
      vs_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      cmake_gen: Ninja Multi-Config
    outputs:
      doc_artifact_name: ${{ steps.set_doc_artifact_name.outputs.doc_artifact_name }}
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qx_package_path=${{ env.qx_build_dir }}/out/dist" >> $Env:GITHUB_ENV
        $qx_install_path="${{ env.qx_build_dir }}/out/install"
        echo "qx_install_path=$qx_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.0
        os: windows
        compiler: msvc2022
        linkage: ${{ matrix.lib_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install Doxygen & Graphviz
      run: |
        choco install doxygen.install --version 1.9.4
        choco install graphviz
    - name: Checkout Qx
      uses: actions/checkout@v3
      with:
        path: ${{ env.qx_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install Qx
      working-directory: ${{ env.qx_src_dir }}
      shell: cmd
      run: |
        echo "Setup C++ Build Environment..."
        CALL "${{ env.vs_dir }}\Common7\Tools\VsDevCmd.bat" -arch=amd64
        echo "Configure CMake using Qt wrapper..."
        CALL "${{ env.qt_cmake }}" -G "${{ env.cmake_gen }}" -S "${{ env.qx_src_dir}}" -B "${{ env.qx_build_dir }}" -D QX_DOCS=ON -D BUILD_SHARED_LIBS=${{ matrix.cmake_bsl }}" 
        echo "Changing to build directory..."
        cd "%qx_build_dir%"
        echo "Building Qx Debug..."
        cmake --build . --target all --config Debug
        echo "Building Qx Relase & Docs ..."
        cmake --build . --target all --config Release
        echo "Installing Qx Debug"
        cmake --install . --config Debug
        echo "Installing Qx Release/Docs..."
        cmake --install . --config Release
        echo "Packaging Qx..."
        cpack -C "Debug;Release"
        echo "Build complete."
    - name: Get Qx artifact name
      run: |
        $artifact_name=$((Get-ChildItem -Path "${{ env.qx_package_path }}" -Filter *.zip)[0].BaseName)
        echo "current_artifact_name=$artifact_name" >> $Env:GITHUB_ENV
    - name: Set doc artifact name
      id: set_doc_artifact_name
      if: matrix.lib_linkage == 'static'
      run: echo "doc_artifact_name=$current_artifact_name" >> $Env:GITHUB_OUTPUT
    - name: Upload Qx build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.qx_install_path }}
        if-no-files-found: error
