name: Build Project
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'
  workflow_run:
    workflows: Tag and Sync
    types: completed
    branches: master

jobs:
  trigger-build:
    name: Build Project
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    uses: oblivioncth/actions/.github/workflows/build-cxx-project.yml@feature/upgrades
    secrets:
      ffynnon_access: ${{ secrets.OBYBOT_FFYNNON_ACCESS }}
  