name: Check Release PR When Opened
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: master

jobs:
  check-pr-correctness:
    name: Release PR correctness check
    runs-on: windows-latest
    steps:
    - name: Ensure higher version
      uses: oblivioncth/actions/cmake/ensure-project-version-gt-tag@dev