name: GitHub Actions Demo
on: [workflow_dispatch]
env:
  main_var: Top

jobs:
  Set-Derived-Variables:
    runs-on: windows-latest
    steps:
      - run: echo "middle_var=${{ env.main_var }}Middle" >> $Env:GITHUB_ENV
      - run: echo "Is there ${{ env.middle_var }}?"

  Use-Derived-Variable-In-Another-Job:
    needs: Set-Derived-Variables
    runs-on: windows-latest
    steps:
      - run: echo "Is there still ${{ env.middle_var }}?"