name: Master pull-request merge reaction
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
env:
  doc_artifact_path: ${{ github.workspace }}/DocArtifact
  artifacts_path: ${{ github.workspace }}/Artifacts
  zips_path: ${{ github.workspace }}/Zips
  
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    outputs:
      version_tag: ${{ steps.tag_master.outputs.new_tag }}
    steps:
    - name: Get project version
      id: get-proj-ver
      uses: oblivioncth/actions/cmake/get-project-version@dev
    - name: Set Git user to ObyBotCI
      uses: oblivioncth/actions/git/set-git-user-to-oby-bot@dev
    - name: Checkout Project
      id: proj-checkout
      uses: oblivioncth/actions/git/smart-checkout@dev
    - name: Tag master with new version tag
      id: tag_master
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      env:
        new_version: ${{ steps.get-proj-ver.outputs.version }}
      run: |
        $new_tag = "v${Env:new_version}"
        echo "new_tag=$new_tag" >> $Env:GITHUB_OUTPUT
        git tag -a $new_tag -m "Release $new_tag"
        git push --tags
    - name: Move 'latest' tag
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      run: |
        echo "Checking for 'latest' tag..."
        if(git tag -l latest){
          echo "Removing previous 'latest' tag..."
          git tag -d latest # Delete tag locally
          git push origin :refs/tags/latest # Delete tag remotely
        }
        else{
          echo "No tag to remove."
        }
        git tag -a latest -m "Latest Release"
        git push origin latest
    - name: Fast-forward merge master into to dev
      if: always()
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      run: |
        git checkout dev
        git merge master --ff-only
        git push
  
  build_qx_release_windows:
    name: Build Qx Release (Windows)
    needs: tag_master_and_sync_dev
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-qx-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}

  build_qx_release_linux:
    name: Build Qx Release (Linux)
    needs: tag_master_and_sync_dev
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-qx-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}

  update-docs:
    name: Update gh-pages
    needs: [build_qx_release_windows]
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    - name: Download built shared Qx artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build_qx_release_windows.outputs.doc_artifact_name }}
        path: ${{ env.doc_artifact_path }}
    - name: Upload docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ${{ env.doc_artifact_path }}/doc/html
        destination_dir: ./docs
        allow_empty_commit: true # So that doc build date is always roughly synced with latest build date
        enable_jekyll: false
        user_name: '${{ env.ci_bot_username}}'
        user_email: '${{ env.ci_bot_email }}'

  create-release:
    name: Create GitHub release
    needs: [update-docs, build_qx_release_windows, build_qx_release_linux, tag_master_and_sync_dev]
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    - name: Download built Qx artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ env.artifacts_path }}
    - name: Zip up release artifacts
      run: |
        $artifact_folders = Get-ChildItem -Directory -Path "${{ env.artifacts_path }}"
        foreach($art_dir in $artifact_folders)
        {
          $name = $art_dir.name
          $path = $art_dir.fullname
          7z a "${{ env.zips_path }}/${name}.zip" "${path}/*"
        }
    - name: Generate release
      uses: softprops/action-gh-release@v1
      with:
        name: "Qx Release ${{ needs.tag_master_and_sync_dev.outputs.version_tag }}"
        tag_name: "${{ needs.tag_master_and_sync_dev.outputs.version_tag }}"
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ${{ env.zips_path }}/*.zip
    
        