name: Qx Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build Qx (Windows)
    uses: ./.github/workflows/build-qx-windows.yml
    secrets:
      qt_shared_url: ${{ secrets.QT_WINDOWS_SHARED_URL }}
      qt_static_url: ${{ secrets.QT_WINDOWS_STATIC_URL }}
   
  trigger-linux-build:
      name: Build Qx (Linux)
      uses: ./.github/workflows/build-qx-linux.yml
      secrets:
        qt_shared_url: ${{ secrets.QT_LINUX_SHARED_URL }}
        qt_static_url: ${{ secrets.QT_LINUX_STATIC_URL }}   