name: Tag and Sync
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
    
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    uses: oblivioncth/actions/.github/workflows/tag-main-and-sync-dev.yml@feature/upgrades